modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/LangQi99/Mekanical-Create/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/LangQi99/Mekanical-Create"
authors="LangQi99"
description='''
通用动力：在 Mekanism 风格的通用动力工厂中，集中执行 Create 的物理加工流程。
Mekanical Create virtualizes Create processing and sequenced assembly inside a configurable factory.
'''

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="[47.1.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="create"
mandatory=true
versionRange="[6.0.8,6.1.0)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="mekanism"
mandatory=true
versionRange="[10.4.16,10.5.0)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="jei"
mandatory=false
versionRange="[15.20,16)"
ordering="AFTER"
side="CLIENT"
